In [55]:
import numpy as np

In [56]:
l=[1,2,3]
print(l)
print(type(l))
a=np.array(l)
print(a)
print(type(a))
a1=np.array([1,2,3])
print(a1)
print(type(a1))


[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


**dtype**

Syntax-> var.dtype

dtype is a variable in array module
#obj>str>complex>float>int>bool
1st it convert the whole array into same datatype using the priority
then it will return the datatype of the array elements.

In [57]:


a3=np.array([True,False])
print(a3)
print(a3.dtype)
a4=np.array([True,False,10])
print(a4)
print(a4.dtype)
a5=np.array([True,False,10,20.67])
print(a5)
print(a5.dtype)
a6=np.array([True,False,10,1+20j])
print(a6)
print(a6.dtype)
a7=np.array([True,10,20j,'abc'])
print(a7)
print(a7.dtype)
a8=np.array([1,2,3,{4,5,5},'abc',20.5,10])
print(a8)
print(a8.dtype)

[ True False]
bool
[ 1  0 10]
int64
[ 1.    0.   10.   20.67]
float64
[ 1. +0.j  0. +0.j 10. +0.j  1.+20.j]
complex128
['True' '10' '20j' 'abc']
<U64
[1 2 3 {4, 5} 'abc' 20.5 10]
object


**ndim**

synatax -> var.ndim

ndim is used to check the dimension of array.

ndim is a variable of array module.


In [58]:
#1-D array
a9=np.array([[1,2,3],[4,5,6]])
print(a9)
print(a9.ndim)
print(a9.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


**shape**

Syntax-> var.shape

Shape is a variable of array module

it will return the shape of the array.


In [59]:
# 2-D array multiple 1-d array form 2-d array
a10=np.array([[1,2,3],[4,5,6]])
print(a10)
print(a10.ndim)
print(a10.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [60]:
# 3-D array multiple 2-d array forms a 3-d array
a11=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(a11)
print(a11.ndim)
print(a11.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3
(2, 3, 3)


**reshape():-**

syntax:-arr_var= arr_var.reshape(rows,cols)

This is a function which is present in a array module

To change rows and column in an existing array we use reshape()

the product of rows and column should be same to the number of value present (before == after repashaping)


In [61]:
a=np.array([[1,2,3,4],
            [5,6,7,8]])
print(a)
a1=a.reshape(4,2)
print(a1)
a=a.reshape(4,2,1) #reshape(no.of_sclice,rows, column)
print(a)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]


**Flatten**

syntax:- aar_var = arr_var.flatten()

this is a function which is present inside the array module

it is used to coverting multidimensional array into unidimensional array

In [62]:
a=np.array([[[1,2,3],
            [4,5,6]],
            [[7,8,9],
            [11,12,13]]])
print(a)
a=a.flatten()
print(a.shape) # shape= no of values or it tell the dimension
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
(12,)
[ 1  2  3  4  5  6  7  8  9 11 12 13]


**ndmin**

syntax:- arr_var= np.array(list_var/list_col, ndim=dimension).reshape(2,4)

(max_dimension=64) (we can use reshape to give rows and col but here also prod of rows and col should be same to no. of value)

this is a parameter present inside array module

this is used to convert uni dimensional to multi dimentional array

ndmin will give result in only in 1 rows and if we are using reshape acc to reshape it will act.

In [63]:
'''a1=np.array([1,2,3,4,5,6,7,8],ndmin=2).reshape(2,4)
print(a1)
print(a1.ndim)'''
a1=np.array([1,2,3,4,5,6,7,8],ndmin=2)
print(a1)
print(a1.ndim)
a1=a1.reshape(2,4)
print(a1)
print(a1.ndim)

[[1 2 3 4 5 6 7 8]]
2
[[1 2 3 4]
 [5 6 7 8]]
2


**arange()**

syntax:-(Sv,av+-1,step val) by default sv=0 and step val=1

it is a function present inside numpy lib

used to  generate sequence of numbers b/w the specified limit

it will give only 1-d array if want to change then can use reshape and also keep on mind that the no. of val generated that should be equal to the product of rows and col you provided inside reshape

In [64]:
a1=np.arange(1,10)
print(a1)
a2=np.arange(1,9,1).reshape(2,4)
print(a2)

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4]
 [5 6 7 8]]


**linspace()**

syntax:- np.linspace(sv,ev,no_of_values)

this is a function. if we don't provide how many no. of values we want by default it will give 50 values

this is present inside numpy lib

it is used to generate equally spaced values b/w the specified limits

In [65]:
a1= np.linspace(1,10,2)
print(a1)
'''a2=np.linspace(1,10) # default no. of values=50
print(a2)
print(len(a2))'''
a3=np.linspace(1,10,5)
print(a3)
a3=a3.reshape(5,1)
print(a3)

[ 1. 10.]
[ 1.    3.25  5.5   7.75 10.  ]
[[ 1.  ]
 [ 3.25]
 [ 5.5 ]
 [ 7.75]
 [10.  ]]


**randint()**

syntax:- arr_var= np.random.randint(sv,ev+1,no_of_values)-1D
(sv,ev+1,(rows,col))-2D (av,ev+1, (slices,rows,col))-3D either we can use these syntax for 2,3-D array or else we can use reshape().

this is a function present inside random module which is present inside numpy lib

this is used to generate random integer numbers b/w the specified limits.



In [66]:
#1-D array
a1=np.random.randint(1,10,5)#.reshape(5,1)
print(a1)
#2-D array
a3=np.random.randint(1,10,(2,3))
print(a3)
#3-D array
a2=np.random.randint(1,10,(2,3,3))
print(a2)

[5 1 2 3 8]
[[9 2 3]
 [9 4 8]]
[[[9 3 6]
  [3 4 9]
  [5 8 4]]

 [[8 8 1]
  [9 2 4]
  [1 7 6]]]


**randn()**

syntax:- arr_var= np.random.randn(no_of_values)

this is present inside the random module which is present inside the numpy lib

use to generate random values b/w -infinity to +infinity

In [67]:
a1=np.random.randn(3,2,5)#(slice,rows,col)
print(a1)

[[[-1.19225130e+00 -5.50707053e-01  1.46314839e-01  3.69074421e-01
   -1.20096036e+00]
  [ 2.34044399e-01 -2.71267578e-01 -1.43390656e-01 -5.03845153e-02
    1.89795957e-03]]

 [[-1.20698460e+00 -8.74258834e-01 -3.66046724e-01 -7.59134696e-02
    3.70662600e-01]
  [-1.60918931e+00 -6.86494526e-02 -9.88583267e-02 -7.65588511e-01
    2.34239474e-01]]

 [[ 8.96755979e-02 -7.31422618e-04 -3.69256852e-01 -1.08275992e-01
    4.73275591e-01]
  [-6.36374072e-01  1.61185917e-01  1.56810472e+00  1.53057499e+00
   -1.35514369e-02]]]


rand()

syntax:- arr_var= np.random.rand(no_of_values)

this is present inside the random module which is present inside the numpy lib

use to generate random values b/w (0,1). It will give only float value

In [68]:
a=np.random.rand(3,2,5)
print(a)

[[[0.09234034 0.85884489 0.91887986 0.76363681 0.90611644]
  [0.51877085 0.9505458  0.73497396 0.22913881 0.62649977]]

 [[0.70680578 0.70249832 0.48244945 0.38586576 0.16309207]
  [0.11603    0.33150992 0.81326287 0.36309692 0.48692264]]

 [[0.57460178 0.66676534 0.72619939 0.34050061 0.21291901]
  [0.93769279 0.10872333 0.61157789 0.97648241 0.62962359]]]


**choice()**

syntax:- arr_var= np.array(list_var/list_col).
  - res=np.random.choice(arr_var).  
  - print(res)  

It is function present inside random module and random module is present inside numpy lib

it is used to fetch random element from the array.

it only works for 1-D array.

In [69]:
a1=np.array([1,2,3,4,5,6])
res=np.random.choice(a1)
print(res)

5


**Shuffle()**

syntax:- arr_var=np.array(list_var/list_col)
- np.random.shuffle(arr.var)
- print(arr_var)

It is function present inside random module and random module is present inside numpy lib.

It is use to shuffle/change the position of aaray randomly.
it has no return type so it will give o/p as none if we use another var to store or print directly.



In [70]:
a1=np.array([1,2,3,4,5,6]) #for 1-D array
np.random.shuffle(a1)
print(a1)
a2=np.array([1,2,3,4,5,6]).reshape(3,2) #for 2-D array
np.random.shuffle(a2)
print(a2)
a3=np.array([1,2,3,4,5,6]).reshape(1,2,3) #for 3-D array
np.random.shuffle(a3)
print(a3)

[2 6 3 5 4 1]
[[1 2]
 [5 6]
 [3 4]]
[[[1 2 3]
  [4 5 6]]]


**copy()**

syntax:- old_arr=np.array(list_var/list_col)
- new_arr= old_arr.copy()

It is a function present inside the array module

use to copy one array elements into another array. but if we do any modification on one array it won't affect on another array.

In [71]:
a1=np.array([1,2,3,4,5,6])
a2=a1.copy()
print(a1)
print(a2)
a1[1]=100
print(a1)
print(a2)
a3=np.array([1,2,3,4,5,6]).reshape(2,3) #for 2-D array
a4=a3.copy()
print(a3)
print(a4)
a3[1][0]=100
print(a3)
print(a4)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[  1 100   3   4   5   6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[  1   2   3]
 [100   5   6]]
[[1 2 3]
 [4 5 6]]


**view()**

syntax:- old_arr=np.array(list_var/list_col)
- new_arr= old_arr.view()

It is a function present inside the array module

use to copy one array elements into another array. but if we do any modification on one array it will affect on another array.

In [72]:
a1=np.array([1,2,3,4,5,6])
a2=a1.view()
print(a1)
print(a2)
a1[1]=100
print(a1)
print(a2)
a3=np.array([1,2,3,4,5,6]).reshape(2,3) #for 2-D array
a4=a3.view()
print(a3)
print(a4)
a3[1][0]=100
print(a3)
print(a4)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[  1 100   3   4   5   6]
[  1 100   3   4   5   6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[  1   2   3]
 [100   5   6]]
[[  1   2   3]
 [100   5   6]]


**Zeros**

syntax:- ar= np.zeros(no_of_values) -!D
        ar= np.zeros((rows, cols)) -2D
        ar= np.zeros((slice, rows, col)) -3D

it is a function present inside numpy lib

used to create an array which consist of only zeros. we pass the values as tuple for 2-D and 3-D array eslse it will throw an error.

In [73]:
a=np.zeros(5) #1-D
print(a)
a1=np.zeros((2,3)) #2-D
print(a1)
a2=np.zeros((3,3,2)) #3-D
print(a2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


**Ones**

syntax:- ar= np.ones(no_of_values) -!D ar= np.ones((rows, cols)) -2D
ar= np.ones((slice, rows, col)) -3D

it is a function present inside numpy lib

used to create an array which consist of only ones. we pass the values as tuple for 2-D and 3-D array eslse it will throw an error.



In [74]:
a=np.ones(5) #1-D
print(a)
a1=np.ones((2,3)) #2-D
print(a1)
a2=np.ones((3,3,2)) #3-D
print(a2)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


**identity**- Primary diagonal consist of 1's remaining 0's

syntax:-arr_var= np.identity(matrix_val) it will take single val as argument.

it is a function present inside nupy lib.

use to create identity matix.

In [75]:
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Functions**
1.array, 2.reshape, 3.flatten, 4.arange, 5.linspace, 6.randint, 7.radin, 8.rand, 9.choice, 10.shuffle, 11.copy, 12.view, 13.zeros, 14.ones, 15.identity

**variable**
1.version, 2.dtype, 3.ndim, 4.shape

**parameters**
1.ndim

**idexing**
1. +ve indexing
2. -ve indexing

for doing indexing in :-

for 1-D array syntax:- arr_var[index_number] (-ve, +ve any can be use)

for 2-D array syntax:- arr_var[row_num][col_num]

for 3-D array syntax:- array_var[slice_num][row_num][col_num]

In [76]:
#1-D array
a=np.array([1,2,3,4,5])
print(a[1])
#2-D array
a1=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a2=a1[0][2]
print(a2)
a3=a1[-1]
print(a3)
a4=a1[-2][-2]
print(a4)

#3-D array
 #row_num  +ve 0,1,2                    #slice_number
#row_num  +ve -3,-2,-1
a5=np.array([[[1,2,3],   #0 or-3
              [4,5,6],   #1 or-2       # 0 or -3
              [7,8,9]],  #2 or-1
             [[11,12,13],  #0 or-3
              [14,15,16],  #1 or-2     # 1 or -2
              [17,18,19]], #2 or-1
             [[20,21,22],  #0 or-3
              [23,24,25],  #1 or-2     # 2 or -1
              [26,27,28]]]) #2 or-1
print(a5[2][1][0])

2
3
[7 8 9]
5
23


**Sclicing**

it used to take multiple element from array.

1-D array sclicing
syntax:-Arr_var[si:ei+-:stepval] where si=stating index, ei= ending index, stepval=updation

2-D array sclicing

syntax:-Arr_var[rowslicing,coslicing]/[si:ei+-:stepval,si:ei+-:stepval]

In [77]:
a1=np.array([1,2,3,4,5])
print(a1)
print(a1[1:4])
print(a1[1:4:1])
print(a1[1:4])
print(a1[1:5:1])
print(a1[-2:-5:-2])
a2=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a2)
print(a2[0:3:2,0:3:2])
print(a2[1:2:1,1:2:1])
print(a2[0:1:1,2:3:1])

[1 2 3 4 5]
[2 3 4]
[2 3 4]
[2 3 4]
[2 3 4 5]
[4 2]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 3]
 [7 9]]
[[5]]
[[3]]


**3-D array slicing**

syntax:-arr_var[slice slicing,row slicing, col slicing]


In [78]:
a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[11,12,13],
              [14,15,16],
              [17,18,19]],
             [[20,21,22],
              [23,24,25],
              [26,27,28]]])
print(a3[0:2:1, 1:2:1, 1:3:1])
print(a3[0:3:2, 1:3:1, 0:2:1])
print(a3[1:2:1, 1:2:1, 1:2:1])
print(a3[0:3:2, 0:3:2, 0:3:2])
print(a3[0:3:1, 0:3:1, 1:2:1])
print(a3[0:3:2, 0:1:1, 0:1:1])
print(a3[0:1:1, 0:3:2, 1:3:1])
print(a3[0:3:1, 1:2:1, 1:2:1])
print(a3[2:3:1, 2:3:1, 2:3:1])

[[[ 5  6]]

 [[15 16]]]
[[[ 4  5]
  [ 7  8]]

 [[23 24]
  [26 27]]]
[[[15]]]
[[[ 1  3]
  [ 7  9]]

 [[20 22]
  [26 28]]]
[[[ 2]
  [ 5]
  [ 8]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]
[[[ 1]]

 [[20]]]
[[[2 3]
  [8 9]]]
[[[ 5]]

 [[15]]

 [[24]]]
[[[28]]]


**Operation on Array**

 - Array to Array operations (Array broad casting)
 - Array with constant
 - Built in functions in Array

 **Array to Array operations**
 - we can do using arthimetic operator and relational operator can also v used

 **Array BroadCasting**
- it is a process of expanding smaller array dimension to match bigger array dimension
- values length should be equal or one , else it will throw error


In [79]:
a1=np.array([1,2,3])
a2=np.array([1,2,3])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1//a2)
print(a1%a2)
print(a1**a2)
print(a1<a2)
print(a1<=a2)
print(a1>a2)
print(a1>=a2)
print(a1==a2)
print(a1!=a2)

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]
[1 1 1]
[0 0 0]
[ 1  4 27]
[False False False]
[ True  True  True]
[False False False]
[ True  True  True]
[ True  True  True]
[False False False]


**Array with constant**
- it will perform operation on each and
- every value present in array with the constant value

note-->
- it will not modify the original array
- it will just return new o/p array

In [80]:
a1=np.array([1,2,3])
print(a1+10)
print(a1-10)
print(a1*10)
print(a1/10)


[11 12 13]
[-9 -8 -7]
[10 20 30]
[0.1 0.2 0.3]


**Inbuilt Funtions on Array**

- arr_var.max()#-->it will return max value in the array
- arr_var.min()#-->it will return min value in the array
- arr_var.mean()#-->it will return avg value in the array
- arr_var.sum()#-->it will return sum values in the array
- abs(a1)#-->it will return absolute value in the array-->converts negative to postive value

In [81]:
a=np.array([-1,-9])
print(abs(a))
print(min(a))
print(max(a))
print(sum(a))
print(a.mean())
print(abs(a))

[1 9]
-9
-1
-10
-5.0
[1 9]
